project:
  title: "simplex-projection-jovi-dev"

format:
  html:
    theme: lumen
    toc: true
    include-in-header:
      - text: |
          <script src="https://tikzjax.com/v1/tikzjax.js" type="text/javascript"></script>
          <link rel="stylesheet" type="text/css" href="https://tikzjax.com/v1/fonts.css">
number-sections: true
number-depth: 2

